name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Final
      id: test-final
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Final
        setup-command: docker-compose up -d
        command: docker exec bdda_api sh -c "pytest"
        timeout: 30
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-FINAL_RESULTS: "${{steps.test-final.outputs.result}}"
      with:
        runners: test-final
